### ISSUE TITLE
FloatView 边界问题

### ISSUE THREAD

**Issue by smileToWxm** [yechaoa/YUtils#9]
设定吸边方式为上下时，没有对左右边界进行越界处理。 可以一直滑动到屏幕外，这样就会导致  view被移动到屏幕外之后无法移动回来。
左右吸边同理！！

**Comment by yechaoa** [comment]
哈喽，目前针对这种场景做了优化，代码已更新，在这个仓库：https://github.com/yechaoa/MaterialDesign。同时，默认拖拽吸边距离为半屏的判断也做了可配置的优化。
